---
abstract: ~
author:
  - 'Sebastian Willert, C<willert@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FirePHP-Dispatcher
no_index:
  directory:
    - inc
    - t
recommends:
  Log::Log4perl: 0
requires:
  Class::Accessor::Fast: 0
  JSON::Any: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_02
